sensor:
  - platform: rest
    name: Soph채mtning k채rl 1
    resource_template: "https://prod-telge-web-apimanagement.azure-api.net/api/thorweb/garbagecollection/schedule/{{ 'Streetname 1, City' | urlencode() }}"
    method: GET
    value_template: >-
      {% set pickups = value_json['Calendar.CalendarItemBasic'] | selectattr("ContainerId", "equalto", "14A") | map(attribute="Date") | list %}
      {% if pickups %}
        {{ pickups | min }}
      {% else %}
        unknown
      {% endif %}
    scan_interval: 43200 # Uppdatera var 12:e timme
    device_class: timestamp
    json_attributes_path: "$.Calendar.CalendarItemBasic"
    json_attributes:
      - Date
      - Title

  - platform: rest
    name: Soph채mtning k채rl 2
    resource_template: "https://prod-telge-web-apimanagement.azure-api.net/api/thorweb/garbagecollection/schedule/{{ 'Streetname 1, City' | urlencode() }}"
    method: GET
    value_template: >-
      {% set pickups = value_json['Calendar.CalendarItemBasic'] | selectattr("ContainerId", "equalto", "15A") | map(attribute="Date") | list %}
      {% if pickups %}
        {{ pickups | min }}
      {% else %}
        unknown
      {% endif %}
    scan_interval: 43200
    device_class: timestamp
    json_attributes_path: "$.Calendar.CalendarItemBasic"
    json_attributes:
      - Date
      - Title
