input_text:
  garbage_collection_address:
    name: Sophamtningsadress
    initial: "VÄGNAMN 1, ORT"

sensor:
  - platform: rest
    name: Sophämtning Kärl 1
    resource_template: >
      {% set address = states('input_text.garbage_collection_address') %}
      https://prod-telge-web-apimanagement.azure-api.net/api/thorweb/garbagecollection/schedule/{{ address | urlencode }}
    method: GET
    headers:
      Accept: "application/json"
    value_template: >-
      {% set today = now().timestamp() %}
      {% set pickups = value_json | selectattr("containerId", "equalto", "14A") | map(attribute="date") | list %}
      {% set future_pickups = pickups | map("as_timestamp") | select("ge", today) | list %}
      {% if future_pickups %}
        {{ future_pickups | min | timestamp_local }}
      {% else %}
        "none"
      {% endif %}
    scan_interval: 43200  # Uppdateras var 12:e timme
    device_class: timestamp
    json_attributes:
      - date
      - containerId
      - title

  - platform: rest
    name: Sophämtning Kärl 2
    resource_template: >
      {% set address = states('input_text.garbage_collection_address') %}
      https://prod-telge-web-apimanagement.azure-api.net/api/thorweb/garbagecollection/schedule/{{ address | urlencode }}
    method: GET
    headers:
      Accept: "application/json"
    value_template: >-
      {% set today = now().timestamp() %}
      {% set pickups = value_json | selectattr("containerId", "equalto", "15A") | map(attribute="date") | list %}
      {% set future_pickups = pickups | map("as_timestamp") | select("ge", today) | list %}
      {% if future_pickups %}
        {{ future_pickups | min | timestamp_local }}
      {% else %}
        "none"
      {% endif %}
    scan_interval: 43200  # Uppdateras var 12:e timme
    device_class: timestamp
    json_attributes:
      - date
      - containerId
      - title
